import { FieldsType } from "@/types/types";
import { regexAddress, regexImage, regexPhone, regexString } from "@/utils/regex";

export const fields: FieldsType = {
  photo: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: false,
    select: true,
    required: false,
    unique: false,
    minLength: 6,
    maxLength: 191,
    regex: regexImage,
    isHashed: false,
    isImage: true,
    isFile: false,
  },
  name: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: true,
    unique: false,
    minLength: 2,
    maxLength: 191,
    regex: regexString,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  country: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: true,
    unique: false,
    minLength: 2,
    maxLength: 191,
    regex: regexString,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  state: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: true,
    unique: false,
    minLength: 2,
    maxLength: 191,
    regex: regexString,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  city: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: true,
    unique: false,
    minLength: 2,
    maxLength: 191,
    regex: regexString,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  zipcode: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: true,
    unique: false,
    minLength: 2,
    maxLength: 20,
    regex: regexString,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  phone: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: true,
    unique: true,
    minLength: 6,
    maxLength: 20,
    regex: regexPhone,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  address: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: false,
    unique: false,
    minLength: 0,
    maxLength: 4096,
    regex: regexAddress,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
};
