import { FieldsType } from "@/types/types";
import { regexBoolean, regexDate, regexNumber, regexString, regexTime } from "@/utils/regex";

export const fields: FieldsType = {
  user: {
    type: Number,
    fk: true,
    parent: "users",
    fkGet: true,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 1,
    maxLength: 15,
    regex: regexNumber,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  title: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: true,
    unique: false,
    minLength: 1,
    maxLength: 191,
    regex: regexString,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  dataDate: {
    type: Date,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: true,
    unique: false,
    minLength: 10,
    maxLength: 10,
    regex: regexDate,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  startTime: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: true,
    unique: false,
    minLength: 5,
    maxLength: 5,
    regex: regexTime,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  endTime: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: true,
    unique: false,
    minLength: 5,
    maxLength: 5,
    regex: regexTime,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  status: {
    type: Boolean,
    fk: false,
    parent: "",
    fkGet: false,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 4,
    maxLength: 5,
    regex: regexBoolean,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
};
