import { FieldsType } from "@/types/types";
import { regexString, regexBoolean } from "@/utils/regex";

export const fields: FieldsType = {
  name: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: true,
    unique: true,
    minLength: 1,
    maxLength: 191,
    regex: regexString,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  description: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: false,
    unique: false,
    minLength: 1,
    maxLength: 191,
    regex: regexString,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  featureCreate: {
    type: Boolean,
    fk: false,
    parent: "",
    fkGet: false,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 4,
    maxLength: 5,
    regex: regexBoolean,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  featureRead: {
    type: Boolean,
    fk: false,
    parent: "",
    fkGet: false,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 4,
    maxLength: 5,
    regex: regexBoolean,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  featureUpdate: {
    type: Boolean,
    fk: false,
    parent: "",
    fkGet: false,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 4,
    maxLength: 5,
    regex: regexBoolean,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  featureDelete: {
    type: Boolean,
    fk: false,
    parent: "",
    fkGet: false,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 4,
    maxLength: 5,
    regex: regexBoolean,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
};
