import { FieldsType } from "@/types/types";
import { regexNumber, regexBoolean, regexString } from "@/utils/regex";

export const fields: FieldsType = {
  role: {
    type: Number,
    fk: true,
    parent: "roles",
    fkGet: true,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 1,
    maxLength: 15,
    regex: regexNumber,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  feature: {
    type: Number,
    fk: true,
    parent: "features",
    fkGet: true,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 1,
    maxLength: 15,
    regex: regexNumber,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  name: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: true,
    unique: false,
    minLength: 1,
    maxLength: 191,
    regex: regexString,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  privilegeCreate: {
    type: Boolean,
    fk: false,
    parent: "",
    fkGet: false,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 4,
    maxLength: 5,
    regex: regexBoolean,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  privilegeRead: {
    type: Boolean,
    fk: false,
    parent: "",
    fkGet: false,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 4,
    maxLength: 5,
    regex: regexBoolean,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  privilegeUpdate: {
    type: Boolean,
    fk: false,
    parent: "",
    fkGet: false,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 4,
    maxLength: 5,
    regex: regexBoolean,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  privilegeDelete: {
    type: Boolean,
    fk: false,
    parent: "",
    fkGet: false,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 4,
    maxLength: 5,
    regex: regexBoolean,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
};
