import { FieldsType } from "@/types/types";
import { regexDate, regexString, regexTime } from "@/utils/regex";

export const fields: FieldsType = {
  title: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: true,
    unique: false,
    minLength: 1,
    maxLength: 191,
    regex: regexString,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  dataDate: {
    type: Date,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: true,
    unique: false,
    minLength: 10,
    maxLength: 10,
    regex: regexDate,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  startTime: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: true,
    unique: false,
    minLength: 5,
    maxLength: 5,
    regex: regexTime,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  endTime: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: true,
    unique: false,
    minLength: 5,
    maxLength: 5,
    regex: regexTime,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
};
