import { FieldsType } from "@/types/types";
import { regexNumber, regexString } from "@/utils/regex";

export const fields: FieldsType = {
  task: {
    type: Number,
    fk: true,
    parent: "tasks",
    fkGet: true,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 1,
    maxLength: 15,
    regex: regexNumber,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  fromPhase: {
    type: Number,
    fk: true,
    parent: "phases",
    fkGet: true,
    search: false,
    select: true,
    required: false, // nullable
    unique: false,
    minLength: 1,
    maxLength: 15,
    regex: regexNumber,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  toPhase: {
    type: Number,
    fk: true,
    parent: "phases",
    fkGet: true,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 1,
    maxLength: 15,
    regex: regexNumber,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  changedBy: {
    type: Number,
    fk: true,
    parent: "users",
    fkGet: true,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 1,
    maxLength: 15,
    regex: regexNumber,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  name: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: false,
    select: true,
    required: true, // uuidv4 required
    unique: false,
    minLength: 1,
    maxLength: 191,
    regex: regexString,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
};
