import { FieldsType } from "@/types/types";
import { regexDate, regexNumber, regexString } from "@/utils/regex";

export const fields: FieldsType = {
  user: {
    type: Number,
    fk: true,
    parent: "users",
    fkGet: true,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 1,
    maxLength: 15,
    regex: regexNumber,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  client: {
    type: Number,
    fk: true,
    parent: "clients",
    fkGet: true,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 1,
    maxLength: 15,
    regex: regexNumber,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  stage: {
    type: Number,
    fk: true,
    parent: "stages",
    fkGet: true,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 1,
    maxLength: 15,
    regex: regexNumber,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  currency: {
    type: Number,
    fk: true,
    parent: "currencies",
    fkGet: true,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 1,
    maxLength: 15,
    regex: regexNumber,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  transactionDate: {
    type: Date,
    fk: false,
    parent: "",
    fkGet: false,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 10, // YYYY-MM-DD
    maxLength: 10,
    regex: regexDate,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  amount: {
    type: Number, // stored as BigInt in DB (cents)
    fk: false,
    parent: "",
    fkGet: false,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 1,
    maxLength: 19, // allow up to 19 digits to be safe
    regex: regexNumber,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  notes: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: false,
    unique: false,
    minLength: 0,
    maxLength: 4096,
    regex: regexString,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  sheet: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: false,
    unique: false,
    minLength: 0,
    maxLength: 191,
    regex: regexString,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  tab: {
    type: Number,
    fk: false,
    parent: "",
    fkGet: false,
    search: false,
    select: true,
    required: false,
    unique: false,
    minLength: 0,
    maxLength: 10,
    regex: regexNumber,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  tabname: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: false,
    unique: false,
    minLength: 0,
    maxLength: 191,
    regex: regexString,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  sheetrow: {
    type: Number,
    fk: false,
    parent: "",
    fkGet: false,
    search: false,
    select: true,
    required: false,
    unique: false,
    minLength: 0,
    maxLength: 10,
    regex: regexNumber,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
};
