import { FieldsType } from "@/types/types";
import { regexAddress, regexEmail, regexImage, regexNumber, regexPassword, regexPhone, regexString } from "@/utils/regex";

export const fields: FieldsType = {
  photo: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: false,
    select: true,
    required: false,
    unique: false,
    minLength: 6,
    maxLength: 191,
    regex: regexImage,
    isHashed: false,
    isImage: true,
    isFile: false,
  },
  role: {
    type: Number,
    fk: true,
    parent: "roles",
    fkGet: false,
    search: false,
    select: false,
    required: true,
    unique: false,
    minLength: 1,
    maxLength: 15,
    regex: regexNumber,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  name: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: true,
    unique: false,
    minLength: 6,
    maxLength: 191,
    regex: regexString,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  email: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: true,
    unique: true,
    minLength: 6,
    maxLength: 191,
    regex: regexEmail,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  password: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: false,
    select: false,
    required: false,
    unique: false,
    minLength: 6,
    maxLength: 191,
    regex: regexPassword,
    isHashed: true,
    isImage: false,
    isFile: false,
  },
  phone: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: false,
    select: true,
    required: true,
    unique: false,
    minLength: 6,
    maxLength: 20,
    regex: regexPhone,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
  address: {
    type: String,
    fk: false,
    parent: "",
    fkGet: false,
    search: true,
    select: true,
    required: true,
    unique: false,
    minLength: 6,
    maxLength: 191,
    regex: regexAddress,
    isHashed: false,
    isImage: false,
    isFile: false,
  },
};
